import _Color from './Color';
import _Language from './Language';
import _RouteNames from './RouteNames';
import _Styles from './Styles';
import _Device from './Device';
import _Images from './Images';
import _Validate from './Validate';
import _Setting from './Setting';
export const Color = _Color;
export const Language = _Language;
export const RouteNames = _RouteNames;
export const Styles = _Styles;
export const Device = _Device;
export const Images = _Images;
export const Validate = _Validate;
export const Setting = _Setting;
