import _SvgAuth1 from './Auth/SvgAuth1';
import _SvgAuth2 from './Auth/SvgAuth2';
import _SvgAuth3 from './Auth/SvgAuth3';
import _Pagination1 from './Auth/Pagination1';
import _Pagination2 from './Auth/Pagination2';
import _Pagination3 from './Auth/Pagination3';
import _Logo from './Auth/Logo';
import _Facebook from './Login/Facebook';
import _Twitter from './Login/Twitter';
import _Google from './Login/Google';
import _AddGroupIcon from './Header/AddGroupIcon';
import _NotificationIcon from './Header/NotificationIcon';
import _InfoIcon from './Header/InfoIcon';
import _ComposeIcon from './Header/ComposeIcon';

export const SvgAuth1 = _SvgAuth1;
export const SvgAuth2 = _SvgAuth2;
export const SvgAuth3 = _SvgAuth3;
export const Pagination1 = _Pagination1;
export const Pagination2 = _Pagination2;
export const Pagination3 = _Pagination3;
export const Logo = _Logo;
export const Facebook = _Facebook;
export const Twitter = _Twitter;
export const Google = _Google;
export const AddGroupIcon = _AddGroupIcon;
export const NotificationIcon = _NotificationIcon;
export const InfoIcon = _InfoIcon;
export const ComposeIcon = _ComposeIcon;
