import _SvgAuth1 from './Auth/SvgAuth1';
import _SvgAuth2 from './Auth/SvgAuth2';
import _SvgAuth3 from './Auth/SvgAuth3';
import _Pagination1 from './Auth/Pagination1';
import _Pagination2 from './Auth/Pagination2';
import _Pagination3 from './Auth/Pagination3';
import _Logo from './Auth/Logo';
export const SvgAuth1 = _SvgAuth1;
export const SvgAuth2 = _SvgAuth2;
export const SvgAuth3 = _SvgAuth3;
export const Pagination1 = _Pagination1;
export const Pagination2 = _Pagination2;
export const Pagination3 = _Pagination3;
export const Logo = _Logo;
